const products = [
  {
    id: "1",
    name: "Laptop",
    price: 999,
    image: "laptop.png",
    description: "High-performance laptop.",
  },
  {
    id: "2",
    name: "Smartphone",
    price: 499,
    image: "smartphone.png",
    description: "Latest model with great features.",
  },
  {
    id: "3",
    name: "Camera",
    price: 549,
    image: "camera.jpg",
    description: "DSLR with great features.",
  },
  {
    id: "4",
    name: "Headphones",
    price: 299,
    image: "headphones.png",
    description: "Noise-cancelling headphones.",
  },
  {
    id: "5",
    name: "Smart Watch",
    price: 199,
    image: "smartwatch.jpg",
    description: "Smart watch with heart rate monitor.",
  },
  {
    id: "6",
    name: "Speaker",
    price: 129,
    image: "speaker.png",
    description: "Bluetooth speaker with high-quality sound.",
  },
  {
    id: "7",
    name: "Tablet",
    price: 599,
    image: "tablet.png",
    description: "Tablet with 10-inch screen.",
  },
  {
    id: "8",
    name: "Keyboard",
    price: 79,
    image: "keyboard.png",
    description: "Wireless mechanical keyboard.",
  },
  {
    id: "9",
    name: "Mouse",
    price: 49,
    image: "mouse.png",
    description: "Wireless optical mouse.",
  },
  {
    id: "10",
    name: "Monitor",
    price: 199,
    image: "monitor.png",
    description: "24-inch computer monitor.",
  },
  {
    id: "11",
    name: "Printer",
    price: 89,
    image: "printer.png",
    description: "Wireless all-in-one printer.",
  },
  {
    id: "12",
    name: "Router",
    price: 69,
    image: "router.png",
    description: "Wireless router with four Ethernet ports.",
  },
];

export default products;
